### ISSUE TITLE
404 not found in configuration

### ISSUE THREAD

**Issue by kilgaloon** [PH2M/GDPR#19]
Link: /admin/system_config/edit/section/phgdpr/

Mentioned link gives me 404 page not found. I use 1.14 Enterprise version, i see that this is tested just for 1.9 but does anybody has a clue what is problem?

**Comment by bastienlm** [comment]
Did you try to access of this section just after logout / login ?

**Comment by kilgaloon** [comment]
Lol, shame on me, that worked 🤦‍♂️

**Comment by bastienlm** [comment]
:smile:
