### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by mbensoussan** [PH2M/GDPR#23]
Bonjour et merci pour ce bout de code assez bien construit !

je suis entrain de testé votre module, et je remarque que lors de l'activation du cookie, quand je vais sur mon site je n'ai pas la question pour accepter les cookies.
je pense que votre module est censé le faire ?

merci de votre retour, je vous ferez part des bug et correctif éventuellement apporté.

**Comment by bastienlm** [comment]
Bonjour,
le module permet bien l'ajout d'une bannière des cookies, mais uniquement si vous décidez d'activer le service Google Analytics
il faut donc la config suivante : 
https://screen.ph2m.fr/screen_2018110289c0.png

une des évolutions possibles serait donc de faire apparaître cette bannière sans être obligé de gérer GA :)

**Comment by mbensoussan** [comment]
-> au final je ne vois pas l'intérêt car magento gère déjà cette barre de cookie. peut être pourrait vous m'éclairer sur ce choix.

-> Concernant l'anonymisation des données, la fonctionnalité semble implémenté mais je ne vois pas comment.

-> je pense qu'a la suppression du compte, c'est un peu violent pour le client. il faudrait après avoir cliqué sur supprimer, avoir un message qui indique que le compte à bien était supprimé (une espèce d'étape de confirmation)

-> Lors de la demande de génération du mot de passe par l'admin magento, ce dernier ne répond pas automatiquement au règle de la CNIL il me semble. y avait vous pensez en modifiant le code de génération ? ou non. Quand est il des mot de passe déjà créé ? si les utilisateurs se connecte ?

-> l'export de donnée, semble pas fonctionné sur les commandes avis ... pouvez vous me confirmer ?

**Comment by bastienlm** [comment]
-> au final je ne vois pas l'intérêt, car Magento gère déjà cette barre de cookie. Peut-être pourrez-vous m'éclairer sur ce choix.
**le gestionnaire de cookies inclut par le module est plus complet et permet notamment l'activation / désactivation de certains cookies pour respecter au mieux la RGPD (https://github.com/AmauriC/tarteaucitron.js)**

-> je pense qu'a la suppression du compte, c'est un peu violent pour le client. il faudrait après avoir cliqué sur supprimer, avoir un message qui indique que le compte à bien était supprimé (une espèce d'étape de confirmation)
**les configurations du module permettent déjà cela :  https://screen.ph2m.fr/screen_20181105a988.png**

-> Lors de la demande de génération du mot de passe par l'admin magento, ce dernier ne répond pas automatiquement aux règles de la CNIL il me semble. Y avait-vous pensez en modifiant le code de génération ? ou non. Quand est il des mot de passe déjà créé ? si les utilisateurs se connecte ?
**Je n'ai pas vérifié, mais il me semble que l'autogénération renvoie bien un mot de passe respectant les règles. 
Concernant les mots de passe déjà créés, le module ne propose pas de solution, c'est au client de mettre en place sa propre solution, s'il souhaite les modifier.** 

-> l'export de donnée, semble pas fonctionné sur les commandes avis ... pouvez vous me confirmer ?
**L'export fonctionne bien, il n'y a cependant pas les avis dans l'export, avez-vous une configuration semblable à : https://screen.ph2m.fr/screen_201811053649.png**

**Comment by mbensoussan** [comment]
merci pour les réponses très claires.
je déploie demain l'ensemble des fonctions et vous fait un retour sur d'éventuelle  bug.

**Comment by bastienlm** [comment]
Je vous conseille de récupérer la prochaine release actuellement sur la branche develop pour profiter des dernières fonctionnalités et correctifs.
