### ISSUE TITLE
Erreur 500 lors de la modification du mot de passe

### ISSUE THREAD

**Issue by jeremiewalter** [PH2M/GDPR#35]
Lorsqu'on essaie de modifier son mot de passe, il y a une erreur 500 lors de la validation.

Message de log : 
`PHP Fatal error:  Uncaught Error: Undefined class constant 'MAXIMUM_PASSWORD_LENGTH' in /var/www/html/sergeblanco/app/code/community/PH2M/Gdpr/Model/Override/Customer/Customer.php:68`

**Comment by bastienlm** [comment]
il faut remplacer `self::MAXIMUM_PASSWORD_LENGTH` par `static::MAXIMUM_PASSWORD_LENGTH`
à la ligne 68 et 69.

Je vais mettre le correctif sur la prochaine version du module, merci du report :)
